### ISSUE TITLE
Links to previous versions of docs

### ISSUE THREAD

**Issue by saulpw** [visidata/visidata.org#4]
Include links to all previous versions of docs at least on /docs.  Ideally on all pages (linking to the previous version of that page, if it exists).

**Comment by anjakefala** [comment]
We have decided to align with jsvine's strategy here: https://github.com/jsvine/intro-to-visidata/issues/27#issuecomment-810632774 for VisiData's tool documentation.

> I'm open to either proposal, though I'm somewhat hesitant to add complexity to this project. VisiData, to me, seems like the kind of software that's best kept updated, with little need to use earlier versions (or cost-prohibition to upgrading).
