### ISSUE TITLE
visidata.org redesign issues

### ISSUE THREAD

**Issue by anjakefala** [visidata/visidata.org#51]
- [x] 1.5.2 manpage (where is 2.x manpage being added/built?)
- [x] redirects (lkhrs said this can be added by 11ty)
- [x] feed.xml 
- [x] /credits link to patreon
- [x] sidebar is underlined (happened when added underlined to `li a` links)
- [x] /docs is missing its second indent bullets (missing the css for it)
- [x] review links in /docs and remove broken ones (e.g. /kblayout viewtsv)

**Comment by lkhrs** [comment]
Re: /credits link to Patreon, I am sure this will fix itself once we move this to production. It works on visidata.netlify.app and my localhost.
