### ISSUE TITLE
Protocol for adding blog posts to the index?

### ISSUE THREAD

**Issue by scotthmurray** [visidata/visidata.org#74]
I just noticed that this release announcement/blog post:

https://www.visidata.org/blog/2022/v2.10.1/
https://github.com/visidata/visidata.org/blob/master/site/blog/2022/v2.10.1.md

…does not yet appear on the blog index page:

https://www.visidata.org/blog/

…nor in the RSS feed.

Is this intentional? It looks like maybe release notes are considered a different sort of "blog post" and are separated on purpose:

<img width="1106" alt="Screen Shot 2022-09-19 at 10 46 12 am" src="https://user-images.githubusercontent.com/1034002/191080915-831a2737-b923-4728-bff3-96179169a1cc.png">

Either way, could you tell me what file to poke at to add posts to either the "Release notes" feed or the "blog posts" feed?

For that matter, note in the "Release notes" feed above, the two most recent posts are showing out of chrono order. I think the v2.10.1 post should be newest and on top.

**Comment by scotthmurray** [comment]
One more question... When announcing vdsql or RSD, since these aren't part of VisiData core, I'd suggest we file those posts as "blog posts" and not "release notes". Then the "release notes" on visidata.org are solely for vd release notes. Sound OK?

**Comment by saulpw** [comment]
Ah yeah, the date on v2.10 is wrong (in the future, even).  I agree, they should be sorted chronologically.  And that vdsql should be a blog post and not a release note.

**Comment by saulpw** [comment]
(and we use the date from the front matter metadata at the top of the post; if the date is changed there then it should be reflected on the site straight away.)

**Comment by lkhrs** [comment]
There’s separate feeds for the releases and blog posts. Are you subscribed to the feed from the Releases page? I’m seeing 2.10 and 2.10.1 in the XML. 

Regarding the chronological issue, the dates need to be switched for 2.10 and 2.10.1 in the frontmatter for those posts. 

Currently, we treat release notes different from blog posts on the frontend, and keep them on their own respective page. The posts are stored in the blog folder because IIRC that’s what the structure was on the old site, and I didn’t want to break the URLs.

**Comment by scotthmurray** [comment]
Thank you both!

@lkhrs I was looking at the wrong RSS feed; thanks for clarifying how this is set up.

I just fixed that release date in PR #75.

So, when crafting a normal blog post (not release notes), is there an extra step needed that adds the post to the index page (and RSS feed)?

**Comment by scotthmurray** [comment]
<img width="542" alt="Screen Shot 2022-09-19 at 11 07 50 am" src="https://user-images.githubusercontent.com/1034002/191084810-fe453123-dc37-4f11-9781-38d9a2d31570.png">

Now I can sleep at night!

**Comment by lkhrs** [comment]
> So, when crafting a normal blog post (not release notes), is there an extra step needed that adds the post to the index page (and RSS feed)?

For normal blog posts, no 🙂

Release notes just need the `releases` tag.

**Comment by scotthmurray** [comment]
Very helpful, thank you!
